# 请求相关配置
http:
  # 从主机读取数据的超时时间(单位: 秒)
  readTimeout: 10
  # 连接主机的超时时间(单位: 秒)
  connectTimeout: 10

  # 代理设置
  proxy:
    # 判断是否启动代理
    isStart: false
    # 代理地址
    host: 127.0.0.1
    # 代理端口
    port: 8080
    # 代理账号
    username: ""
    # 代理密码
    password: ""

  # 扫描协议
  scanProtocol:
    # 用于判断是否启动 http 协议,进行 host 碰撞
    isScanHttp: true
    # 用于判断是否启动 https 协议,进行 host 碰撞
    isScanHttps: true

  # 绝对错误的host地址
  # 没事不要改它, 实在要改也要改成一个绝对不可能解析的成功的地址
  errorHost: "error.miaohosttest666666.com"

  # 相对主机名
  # 没事也不用改它, 拿来做二次匹配的
  relativeHostName: "q1w2e3sr4."

# 相似度比例
# 1 = 100%, 0.7 = 70%
# 主要用来 host碰撞请求 对比 原请求 与 绝对host错误请求的相似度 超过多少会被认为不存在该问题
# 例如:
#   host碰撞请求 与 原请求 相似度超过0.7则认为不存在该问题
#   host碰撞请求 与 绝对host错误请求的 相似度超过0.7则认为不存在该问题
similarityRatio: 0.7

# 程序运行的最大线程总数
# 最小值为1, 小于等于0, 会重置为1
# 注意:
#   会自动根据输入的ip总数,来动态启动线程执行任务
#   设置6的话,意思是最多可以开几个线程来执行任务的意思
threadTotal: 6

# host碰撞的数据来源地址
dataSource:
  # ip 数据来源地址
  ipFilePath: "./dataSource/ipList.txt"
  # host 数据来源地址
  hostFilePath: "./dataSource/hostList.txt"

# 默认的结果输出格式
# 格式有二种分别是 csv, txt
defaultResultOutput:
  isOutputCsv: true
  isOutputTxt: true

# 判断是否将错误日志输出
# 开启以后 站点访问失败/host碰撞失败 的结果都会输出到命令行中,方便实时查看
isOutputErrorLog: true

# 认为碰撞成功的状态码
# 支持使用逗号分割多个状态码<例如: 200,301,302>
# 为空表示关闭该功能
# 注: 开启该功能可以在某些场景获得更好的体验
collisionSuccessStatusCode: "200,301,302"